version: "2"

services:
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
  pgsql:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

